apiVersion: v1  
kind: Pod 
metadata:
  name: envfrom-secret
spec:
  containers:
  - name: milal-mysql
    image: mysql
    envFrom:
    - secretRef:
        name: milal-ebs-id-secret
    - secretRef:
        name: milal-ec2-vol-id-secret