apiVersion: v1
kind: Pod
metadata:
  name: milal-client
  labels:
    app: milal-client
spec:
  containers:
    - name: react-app
      image: tlsskfk/milal-client:v1.1.144
      env:
        - name: PROXY_ADDRESS
          value: "http://api-svc:8600"